[general]
email = "justin.tauvron@outlook.fr"  # Adresse e-mail pour les notifications
enableCORS = false  # Activer ou désactiver le support CORS (Cross-Origin Resource Sharing)

[server]
headless = true  # Exécution en mode headless
port = 80  # Port sur lequel l'application sera exposée
enableXsrfProtection = true  # Activer la protection contre les attaques XSRF

[browser]
serverAddress = "0.0.0.0"  # Adresse IP du serveur

[global]
logLevel = "info"  # Niveau de journalisation (debug, info, warning, error, critical)

